name: 'dbt_snowflake_airflow_project'
version: '1.0.0'
profile: 'dbt_snowflake_airflow_project'

packages-install-path: /tmp/dbt_packages

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_snowflake_airflow_project:
    staging:
      +materialized: view
      +snowflake_warehouse: dbt_wh
    marts:
      +materialized: table
      +snowflake_warehouse: dbt_wh
